//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.Controller
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.Controller.ControllerService")]
    public interface ControllerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName1> getStateAsync(Ihc.Soap.Controller.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enterProjectChangeMode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName2> enterProjectChangeModeAsync(Ihc.Soap.Controller.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exitProjectChangeMode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName3> exitProjectChangeModeAsync(Ihc.Soap.Controller.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="isIHCProjectAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName4> isIHCProjectAvailableAsync(Ihc.Soap.Controller.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName5> getIHCProjectSegmentAsync(Ihc.Soap.Controller.inputMessageName5 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="storeIHCProjectSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName6> storeIHCProjectSegmentAsync(Ihc.Soap.Controller.inputMessageName6 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectSegmentationSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName7> getIHCProjectSegmentationSizeAsync(Ihc.Soap.Controller.inputMessageName7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectNumberOfSegments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName8> getIHCProjectNumberOfSegmentsAsync(Ihc.Soap.Controller.inputMessageName8 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="waitForControllerStateChange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName9> waitForControllerStateChangeAsync(Ihc.Soap.Controller.inputMessageName9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="storeIHCProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName10> storeIHCProjectAsync(Ihc.Soap.Controller.inputMessageName10 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName11> getProjectInfoAsync(Ihc.Soap.Controller.inputMessageName11 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName12> getIHCProjectAsync(Ihc.Soap.Controller.inputMessageName12 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSControllerState
    {
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSDate
    {
        
        private int dayField;
        
        private int minutesField;
        
        private int hoursField;
        
        private int secondsField;
        
        private int yearField;
        
        private int monthWithJanuaryAsOneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int monthWithJanuaryAsOne
        {
            get
            {
                return this.monthWithJanuaryAsOneField;
            }
            set
            {
                this.monthWithJanuaryAsOneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSProjectInfo
    {
        
        private int visualMinorVersionField;
        
        private int visualMajorVersionField;
        
        private int projectMajorRevisionField;
        
        private int projectMinorRevisionField;
        
        private WSDate lastmodifiedField;
        
        private string projectNumberField;
        
        private string customerNameField;
        
        private string installerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int visualMinorVersion
        {
            get
            {
                return this.visualMinorVersionField;
            }
            set
            {
                this.visualMinorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int visualMajorVersion
        {
            get
            {
                return this.visualMajorVersionField;
            }
            set
            {
                this.visualMajorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int projectMajorRevision
        {
            get
            {
                return this.projectMajorRevisionField;
            }
            set
            {
                this.projectMajorRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int projectMinorRevision
        {
            get
            {
                return this.projectMinorRevisionField;
            }
            set
            {
                this.projectMinorRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public WSDate lastmodified
        {
            get
            {
                return this.lastmodifiedField;
            }
            set
            {
                this.lastmodifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string projectNumber
        {
            get
            {
                return this.projectNumberField;
            }
            set
            {
                this.projectNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string installerName
        {
            get
            {
                return this.installerNameField;
            }
            set
            {
                this.installerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSFile
    {
        
        private byte[] dataField;
        
        private string filenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        public inputMessageName1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSControllerState getState1;
        
        public outputMessageName1()
        {
        }
        
        public outputMessageName1(Ihc.Soap.Controller.WSControllerState getState1)
        {
            this.getState1 = getState1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        public inputMessageName2()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> enterProjectChangeMode1;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(System.Nullable<bool> enterProjectChangeMode1)
        {
            this.enterProjectChangeMode1 = enterProjectChangeMode1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        public inputMessageName3()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> exitProjectChangeMode1;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(System.Nullable<bool> exitProjectChangeMode1)
        {
            this.exitProjectChangeMode1 = exitProjectChangeMode1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        public inputMessageName4()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isIHCProjectAvailable1;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(System.Nullable<bool> isIHCProjectAvailable1)
        {
            this.isIHCProjectAvailable1 = isIHCProjectAvailable1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment3;
        
        public inputMessageName5()
        {
        }
        
        public inputMessageName5(System.Nullable<int> getIHCProjectSegment1, System.Nullable<int> getIHCProjectSegment2, System.Nullable<int> getIHCProjectSegment3)
        {
            this.getIHCProjectSegment1 = getIHCProjectSegment1;
            this.getIHCProjectSegment2 = getIHCProjectSegment2;
            this.getIHCProjectSegment3 = getIHCProjectSegment3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSFile getIHCProjectSegment4;
        
        public outputMessageName5()
        {
        }
        
        public outputMessageName5(Ihc.Soap.Controller.WSFile getIHCProjectSegment4)
        {
            this.getIHCProjectSegment4 = getIHCProjectSegment4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSFile storeIHCProjectSegment1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> storeIHCProjectSegment2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> storeIHCProjectSegment3;
        
        public inputMessageName6()
        {
        }
        
        public inputMessageName6(Ihc.Soap.Controller.WSFile storeIHCProjectSegment1, System.Nullable<int> storeIHCProjectSegment2, System.Nullable<int> storeIHCProjectSegment3)
        {
            this.storeIHCProjectSegment1 = storeIHCProjectSegment1;
            this.storeIHCProjectSegment2 = storeIHCProjectSegment2;
            this.storeIHCProjectSegment3 = storeIHCProjectSegment3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> storeIHCProjectSegment4;
        
        public outputMessageName6()
        {
        }
        
        public outputMessageName6(System.Nullable<bool> storeIHCProjectSegment4)
        {
            this.storeIHCProjectSegment4 = storeIHCProjectSegment4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName7
    {
        
        public inputMessageName7()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegmentationSize1;
        
        public outputMessageName7()
        {
        }
        
        public outputMessageName7(System.Nullable<int> getIHCProjectSegmentationSize1)
        {
            this.getIHCProjectSegmentationSize1 = getIHCProjectSegmentationSize1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName8
    {
        
        public inputMessageName8()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName8
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectNumberOfSegments1;
        
        public outputMessageName8()
        {
        }
        
        public outputMessageName8(System.Nullable<int> getIHCProjectNumberOfSegments1)
        {
            this.getIHCProjectNumberOfSegments1 = getIHCProjectNumberOfSegments1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSControllerState waitForControllerStateChange1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> waitForControllerStateChange2;
        
        public inputMessageName9()
        {
        }
        
        public inputMessageName9(Ihc.Soap.Controller.WSControllerState waitForControllerStateChange1, System.Nullable<int> waitForControllerStateChange2)
        {
            this.waitForControllerStateChange1 = waitForControllerStateChange1;
            this.waitForControllerStateChange2 = waitForControllerStateChange2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSControllerState waitForControllerStateChange3;
        
        public outputMessageName9()
        {
        }
        
        public outputMessageName9(Ihc.Soap.Controller.WSControllerState waitForControllerStateChange3)
        {
            this.waitForControllerStateChange3 = waitForControllerStateChange3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSFile storeIHCProject1;
        
        public inputMessageName10()
        {
        }
        
        public inputMessageName10(Ihc.Soap.Controller.WSFile storeIHCProject1)
        {
            this.storeIHCProject1 = storeIHCProject1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> storeIHCProject2;
        
        public outputMessageName10()
        {
        }
        
        public outputMessageName10(System.Nullable<bool> storeIHCProject2)
        {
            this.storeIHCProject2 = storeIHCProject2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName11
    {
        
        public inputMessageName11()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName11
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSProjectInfo getProjectInfo1;
        
        public outputMessageName11()
        {
        }
        
        public outputMessageName11(Ihc.Soap.Controller.WSProjectInfo getProjectInfo1)
        {
            this.getProjectInfo1 = getProjectInfo1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName12
    {
        
        public inputMessageName12()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName12
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Controller.WSFile getIHCProject1;
        
        public outputMessageName12()
        {
        }
        
        public outputMessageName12(Ihc.Soap.Controller.WSFile getIHCProject1)
        {
            this.getIHCProject1 = getIHCProject1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ControllerServiceChannel : Ihc.Soap.Controller.ControllerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ControllerServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.Controller.ControllerService>, Ihc.Soap.Controller.ControllerService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ControllerServiceClient() : 
                base(ControllerServiceClient.GetDefaultBinding(), ControllerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ControllerServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControllerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ControllerServiceClient.GetBindingForEndpoint(endpointConfiguration), ControllerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControllerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ControllerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControllerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ControllerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControllerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName1> Ihc.Soap.Controller.ControllerService.getStateAsync(Ihc.Soap.Controller.inputMessageName1 request)
        {
            return base.Channel.getStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName1> getStateAsync()
        {
            Ihc.Soap.Controller.inputMessageName1 inValue = new Ihc.Soap.Controller.inputMessageName1();
            return ((Ihc.Soap.Controller.ControllerService)(this)).getStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName2> Ihc.Soap.Controller.ControllerService.enterProjectChangeModeAsync(Ihc.Soap.Controller.inputMessageName2 request)
        {
            return base.Channel.enterProjectChangeModeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName2> enterProjectChangeModeAsync()
        {
            Ihc.Soap.Controller.inputMessageName2 inValue = new Ihc.Soap.Controller.inputMessageName2();
            return ((Ihc.Soap.Controller.ControllerService)(this)).enterProjectChangeModeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName3> Ihc.Soap.Controller.ControllerService.exitProjectChangeModeAsync(Ihc.Soap.Controller.inputMessageName3 request)
        {
            return base.Channel.exitProjectChangeModeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName3> exitProjectChangeModeAsync()
        {
            Ihc.Soap.Controller.inputMessageName3 inValue = new Ihc.Soap.Controller.inputMessageName3();
            return ((Ihc.Soap.Controller.ControllerService)(this)).exitProjectChangeModeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName4> Ihc.Soap.Controller.ControllerService.isIHCProjectAvailableAsync(Ihc.Soap.Controller.inputMessageName4 request)
        {
            return base.Channel.isIHCProjectAvailableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName4> isIHCProjectAvailableAsync()
        {
            Ihc.Soap.Controller.inputMessageName4 inValue = new Ihc.Soap.Controller.inputMessageName4();
            return ((Ihc.Soap.Controller.ControllerService)(this)).isIHCProjectAvailableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName5> Ihc.Soap.Controller.ControllerService.getIHCProjectSegmentAsync(Ihc.Soap.Controller.inputMessageName5 request)
        {
            return base.Channel.getIHCProjectSegmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName5> getIHCProjectSegmentAsync(System.Nullable<int> getIHCProjectSegment1, System.Nullable<int> getIHCProjectSegment2, System.Nullable<int> getIHCProjectSegment3)
        {
            Ihc.Soap.Controller.inputMessageName5 inValue = new Ihc.Soap.Controller.inputMessageName5();
            inValue.getIHCProjectSegment1 = getIHCProjectSegment1;
            inValue.getIHCProjectSegment2 = getIHCProjectSegment2;
            inValue.getIHCProjectSegment3 = getIHCProjectSegment3;
            return ((Ihc.Soap.Controller.ControllerService)(this)).getIHCProjectSegmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName6> Ihc.Soap.Controller.ControllerService.storeIHCProjectSegmentAsync(Ihc.Soap.Controller.inputMessageName6 request)
        {
            return base.Channel.storeIHCProjectSegmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName6> storeIHCProjectSegmentAsync(Ihc.Soap.Controller.WSFile storeIHCProjectSegment1, System.Nullable<int> storeIHCProjectSegment2, System.Nullable<int> storeIHCProjectSegment3)
        {
            Ihc.Soap.Controller.inputMessageName6 inValue = new Ihc.Soap.Controller.inputMessageName6();
            inValue.storeIHCProjectSegment1 = storeIHCProjectSegment1;
            inValue.storeIHCProjectSegment2 = storeIHCProjectSegment2;
            inValue.storeIHCProjectSegment3 = storeIHCProjectSegment3;
            return ((Ihc.Soap.Controller.ControllerService)(this)).storeIHCProjectSegmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName7> Ihc.Soap.Controller.ControllerService.getIHCProjectSegmentationSizeAsync(Ihc.Soap.Controller.inputMessageName7 request)
        {
            return base.Channel.getIHCProjectSegmentationSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName7> getIHCProjectSegmentationSizeAsync()
        {
            Ihc.Soap.Controller.inputMessageName7 inValue = new Ihc.Soap.Controller.inputMessageName7();
            return ((Ihc.Soap.Controller.ControllerService)(this)).getIHCProjectSegmentationSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName8> Ihc.Soap.Controller.ControllerService.getIHCProjectNumberOfSegmentsAsync(Ihc.Soap.Controller.inputMessageName8 request)
        {
            return base.Channel.getIHCProjectNumberOfSegmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName8> getIHCProjectNumberOfSegmentsAsync()
        {
            Ihc.Soap.Controller.inputMessageName8 inValue = new Ihc.Soap.Controller.inputMessageName8();
            return ((Ihc.Soap.Controller.ControllerService)(this)).getIHCProjectNumberOfSegmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName9> Ihc.Soap.Controller.ControllerService.waitForControllerStateChangeAsync(Ihc.Soap.Controller.inputMessageName9 request)
        {
            return base.Channel.waitForControllerStateChangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName9> waitForControllerStateChangeAsync(Ihc.Soap.Controller.WSControllerState waitForControllerStateChange1, System.Nullable<int> waitForControllerStateChange2)
        {
            Ihc.Soap.Controller.inputMessageName9 inValue = new Ihc.Soap.Controller.inputMessageName9();
            inValue.waitForControllerStateChange1 = waitForControllerStateChange1;
            inValue.waitForControllerStateChange2 = waitForControllerStateChange2;
            return ((Ihc.Soap.Controller.ControllerService)(this)).waitForControllerStateChangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName10> Ihc.Soap.Controller.ControllerService.storeIHCProjectAsync(Ihc.Soap.Controller.inputMessageName10 request)
        {
            return base.Channel.storeIHCProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName10> storeIHCProjectAsync(Ihc.Soap.Controller.WSFile storeIHCProject1)
        {
            Ihc.Soap.Controller.inputMessageName10 inValue = new Ihc.Soap.Controller.inputMessageName10();
            inValue.storeIHCProject1 = storeIHCProject1;
            return ((Ihc.Soap.Controller.ControllerService)(this)).storeIHCProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName11> Ihc.Soap.Controller.ControllerService.getProjectInfoAsync(Ihc.Soap.Controller.inputMessageName11 request)
        {
            return base.Channel.getProjectInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName11> getProjectInfoAsync()
        {
            Ihc.Soap.Controller.inputMessageName11 inValue = new Ihc.Soap.Controller.inputMessageName11();
            return ((Ihc.Soap.Controller.ControllerService)(this)).getProjectInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName12> Ihc.Soap.Controller.ControllerService.getIHCProjectAsync(Ihc.Soap.Controller.inputMessageName12 request)
        {
            return base.Channel.getIHCProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Controller.outputMessageName12> getIHCProjectAsync()
        {
            Ihc.Soap.Controller.inputMessageName12 inValue = new Ihc.Soap.Controller.inputMessageName12();
            return ((Ihc.Soap.Controller.ControllerService)(this)).getIHCProjectAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControllerServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControllerServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ControllerService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ControllerServiceClient.GetBindingForEndpoint(EndpointConfiguration.ControllerServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ControllerServiceClient.GetEndpointAddress(EndpointConfiguration.ControllerServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ControllerServiceBindingPort,
        }
    }
}
