//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.OpenApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.OpenApi.OpenAPIService")]
    public interface OpenAPIService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="setValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName1> setValuesAsync(Ihc.Soap.OpenApi.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName2> getValuesAsync(Ihc.Soap.OpenApi.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="waitForEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName3> waitForEventsAsync(Ihc.Soap.OpenApi.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName4> getTimeAsync(Ihc.Soap.OpenApi.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUptime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName5> getUptimeAsync(Ihc.Soap.OpenApi.inputMessageName5 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName6> pingAsync(Ihc.Soap.OpenApi.inputMessageName6 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getFWVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName7> getFWVersionAsync(Ihc.Soap.OpenApi.inputMessageName7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAPIVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName8> getAPIVersionAsync(Ihc.Soap.OpenApi.inputMessageName8 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName9> authenticateAsync(Ihc.Soap.OpenApi.inputMessageName9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName10> getProjectInfoAsync(Ihc.Soap.OpenApi.inputMessageName10 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enableSubscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName11> enableSubscriptionAsync(Ihc.Soap.OpenApi.inputMessageName11 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="disableSubscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName12> disableSubscriptionAsync(Ihc.Soap.OpenApi.inputMessageName12 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDatalineInputIDs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName13> getDatalineInputIDsAsync(Ihc.Soap.OpenApi.inputMessageName13 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDatalineOutputIDs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName14> getDatalineOutputIDsAsync(Ihc.Soap.OpenApi.inputMessageName14 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="isIHCProjectAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName15> isIHCProjectAvailableAsync(Ihc.Soap.OpenApi.inputMessageName15 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName16> getIHCProjectSegmentAsync(Ihc.Soap.OpenApi.inputMessageName16 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectSegmentationSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName17> getIHCProjectSegmentationSizeAsync(Ihc.Soap.OpenApi.inputMessageName17 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getIHCProjectNumberOfSegments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName18> getIHCProjectNumberOfSegmentsAsync(Ihc.Soap.OpenApi.inputMessageName18 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSceneProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName19> getSceneProjectInfoAsync(Ihc.Soap.OpenApi.inputMessageName19 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSceneProjectSegmentationSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName20> getSceneProjectSegmentationSizeAsync(Ihc.Soap.OpenApi.inputMessageName20 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSceneProjectSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName21> getSceneProjectSegmentAsync(Ihc.Soap.OpenApi.inputMessageName21 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSResourceValueEvent
    {
        
        private int m_resourceIDField;
        
        private WSResourceValue m_valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int m_resourceID
        {
            get
            {
                return this.m_resourceIDField;
            }
            set
            {
                this.m_resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public WSResourceValue m_value
        {
            get
            {
                return this.m_valueField;
            }
            set
            {
                this.m_valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSBooleanValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSDateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSEnumValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSFloatingPointValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSIntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSPhoneNumberValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneDimmerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneRelayValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneShutterSimpleValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSTimerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSTimeValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSWeekdayValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSResourceValue
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSSceneProjectInfo
    {
        
        private string nameField;
        
        private int sizeField;
        
        private string versionField;
        
        private WSDate createdField;
        
        private WSDate lastmodifiedField;
        
        private string descriptionField;
        
        private string filepathField;
        
        private bool remoteField;
        
        private long crcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public WSDate created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public WSDate lastmodified
        {
            get
            {
                return this.lastmodifiedField;
            }
            set
            {
                this.lastmodifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string filepath
        {
            get
            {
                return this.filepathField;
            }
            set
            {
                this.filepathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool remote
        {
            get
            {
                return this.remoteField;
            }
            set
            {
                this.remoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long crc
        {
            get
            {
                return this.crcField;
            }
            set
            {
                this.crcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSDate
    {
        
        private int hoursField;
        
        private int minutesField;
        
        private int secondsField;
        
        private int yearField;
        
        private int dayField;
        
        private int monthWithJanuaryAsOneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int monthWithJanuaryAsOne
        {
            get
            {
                return this.monthWithJanuaryAsOneField;
            }
            set
            {
                this.monthWithJanuaryAsOneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSFile
    {
        
        private string filenameField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSDatalineResource
    {
        
        private int datalineNumberField;
        
        private int resourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int datalineNumber
        {
            get
            {
                return this.datalineNumberField;
            }
            set
            {
                this.datalineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int resourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSProjectInfo
    {
        
        private int visualMinorVersionField;
        
        private int visualMajorVersionField;
        
        private int projectMajorRevisionField;
        
        private int projectMinorRevisionField;
        
        private WSDate lastmodifiedField;
        
        private string projectNumberField;
        
        private string customerNameField;
        
        private string installerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int visualMinorVersion
        {
            get
            {
                return this.visualMinorVersionField;
            }
            set
            {
                this.visualMinorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int visualMajorVersion
        {
            get
            {
                return this.visualMajorVersionField;
            }
            set
            {
                this.visualMajorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int projectMajorRevision
        {
            get
            {
                return this.projectMajorRevisionField;
            }
            set
            {
                this.projectMajorRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int projectMinorRevision
        {
            get
            {
                return this.projectMinorRevisionField;
            }
            set
            {
                this.projectMinorRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public WSDate lastmodified
        {
            get
            {
                return this.lastmodifiedField;
            }
            set
            {
                this.lastmodifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string projectNumber
        {
            get
            {
                return this.projectNumberField;
            }
            set
            {
                this.projectNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string installerName
        {
            get
            {
                return this.installerNameField;
            }
            set
            {
                this.installerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSVersionInfo
    {
        
        private int majorVersionField;
        
        private int minorVersionField;
        
        private int buildVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int majorVersion
        {
            get
            {
                return this.majorVersionField;
            }
            set
            {
                this.majorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int minorVersion
        {
            get
            {
                return this.minorVersionField;
            }
            set
            {
                this.minorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int buildVersion
        {
            get
            {
                return this.buildVersionField;
            }
            set
            {
                this.buildVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSEventPackage
    {
        
        private WSResourceValueEvent[] resourceValueEventsField;
        
        private bool controllerExecutionRunningField;
        
        private int subscriptionAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public WSResourceValueEvent[] resourceValueEvents
        {
            get
            {
                return this.resourceValueEventsField;
            }
            set
            {
                this.resourceValueEventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool controllerExecutionRunning
        {
            get
            {
                return this.controllerExecutionRunningField;
            }
            set
            {
                this.controllerExecutionRunningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int subscriptionAmount
        {
            get
            {
                return this.subscriptionAmountField;
            }
            set
            {
                this.subscriptionAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSBooleanValue : WSResourceValue
    {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSDateValue : WSResourceValue
    {
        
        private short yearField;
        
        private sbyte monthField;
        
        private sbyte dayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sbyte month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public sbyte day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSEnumValue : WSResourceValue
    {
        
        private int enumValueIDField;
        
        private string enumNameField;
        
        private int definitionTypeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int enumValueID
        {
            get
            {
                return this.enumValueIDField;
            }
            set
            {
                this.enumValueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string enumName
        {
            get
            {
                return this.enumNameField;
            }
            set
            {
                this.enumNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int definitionTypeID
        {
            get
            {
                return this.definitionTypeIDField;
            }
            set
            {
                this.definitionTypeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSFloatingPointValue : WSResourceValue
    {
        
        private double maximumValueField;
        
        private double minimumValueField;
        
        private double floatingPointValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double maximumValue
        {
            get
            {
                return this.maximumValueField;
            }
            set
            {
                this.maximumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double minimumValue
        {
            get
            {
                return this.minimumValueField;
            }
            set
            {
                this.minimumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double floatingPointValue
        {
            get
            {
                return this.floatingPointValueField;
            }
            set
            {
                this.floatingPointValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSIntegerValue : WSResourceValue
    {
        
        private int integerField;
        
        private int maximumValueField;
        
        private int minimumValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int integer
        {
            get
            {
                return this.integerField;
            }
            set
            {
                this.integerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maximumValue
        {
            get
            {
                return this.maximumValueField;
            }
            set
            {
                this.maximumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int minimumValue
        {
            get
            {
                return this.minimumValueField;
            }
            set
            {
                this.minimumValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSPhoneNumberValue : WSResourceValue
    {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneDimmerValue : WSResourceValue
    {
        
        private int dimmerPercentageField;
        
        private int rampTimeField;
        
        private int delayTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int dimmerPercentage
        {
            get
            {
                return this.dimmerPercentageField;
            }
            set
            {
                this.dimmerPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int rampTime
        {
            get
            {
                return this.rampTimeField;
            }
            set
            {
                this.rampTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneRelayValue : WSResourceValue
    {
        
        private int delayTimeField;
        
        private bool relayValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool relayValue
        {
            get
            {
                return this.relayValueField;
            }
            set
            {
                this.relayValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneShutterSimpleValue : WSResourceValue
    {
        
        private bool shutterPositionIsUpField;
        
        private int delayTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool shutterPositionIsUp
        {
            get
            {
                return this.shutterPositionIsUpField;
            }
            set
            {
                this.shutterPositionIsUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSTimerValue : WSResourceValue
    {
        
        private long millisecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long milliseconds
        {
            get
            {
                return this.millisecondsField;
            }
            set
            {
                this.millisecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSTimeValue : WSResourceValue
    {
        
        private int hoursField;
        
        private int minutesField;
        
        private int secondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSWeekdayValue : WSResourceValue
    {
        
        private int weekdayNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int weekdayNumber
        {
            get
            {
                return this.weekdayNumberField;
            }
            set
            {
                this.weekdayNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.OpenApi.WSResourceValueEvent[] setValues1;
        
        public inputMessageName1()
        {
        }
        
        public inputMessageName1(Ihc.Soap.OpenApi.WSResourceValueEvent[] setValues1)
        {
            this.setValues1 = setValues1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> setValues2;
        
        public outputMessageName1()
        {
        }
        
        public outputMessageName1(System.Nullable<bool> setValues2)
        {
            this.setValues2 = setValues2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] getValues1;
        
        public inputMessageName2()
        {
        }
        
        public inputMessageName2(int[] getValues1)
        {
            this.getValues1 = getValues1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="utcs.values")]
        public Ihc.Soap.OpenApi.WSResourceValue[] getValues2;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(Ihc.Soap.OpenApi.WSResourceValue[] getValues2)
        {
            this.getValues2 = getValues2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> waitForEvents1;
        
        public inputMessageName3()
        {
        }
        
        public inputMessageName3(System.Nullable<int> waitForEvents1)
        {
            this.waitForEvents1 = waitForEvents1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSEventPackage waitForEvents2;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(Ihc.Soap.OpenApi.WSEventPackage waitForEvents2)
        {
            this.waitForEvents2 = waitForEvents2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        public inputMessageName4()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSDate getTime1;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(Ihc.Soap.OpenApi.WSDate getTime1)
        {
            this.getTime1 = getTime1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        public inputMessageName5()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> getUptime1;
        
        public outputMessageName5()
        {
        }
        
        public outputMessageName5(System.Nullable<long> getUptime1)
        {
            this.getUptime1 = getUptime1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName6
    {
        
        public inputMessageName6()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName6
    {
        
        public outputMessageName6()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName7
    {
        
        public inputMessageName7()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSVersionInfo getFWVersion1;
        
        public outputMessageName7()
        {
        }
        
        public outputMessageName7(Ihc.Soap.OpenApi.WSVersionInfo getFWVersion1)
        {
            this.getFWVersion1 = getFWVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName8
    {
        
        public inputMessageName8()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName8
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getAPIVersion1;
        
        public outputMessageName8()
        {
        }
        
        public outputMessageName8(System.Nullable<int> getAPIVersion1)
        {
            this.getAPIVersion1 = getAPIVersion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authenticate1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authenticate2;
        
        public inputMessageName9()
        {
        }
        
        public inputMessageName9(string authenticate1, string authenticate2)
        {
            this.authenticate1 = authenticate1;
            this.authenticate2 = authenticate2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> authenticate3;
        
        public outputMessageName9()
        {
        }
        
        public outputMessageName9(System.Nullable<bool> authenticate3)
        {
            this.authenticate3 = authenticate3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName10
    {
        
        public inputMessageName10()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSProjectInfo getProjectInfo1;
        
        public outputMessageName10()
        {
        }
        
        public outputMessageName10(Ihc.Soap.OpenApi.WSProjectInfo getProjectInfo1)
        {
            this.getProjectInfo1 = getProjectInfo1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName11
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] enableSubscription1;
        
        public inputMessageName11()
        {
        }
        
        public inputMessageName11(int[] enableSubscription1)
        {
            this.enableSubscription1 = enableSubscription1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName11
    {
        
        public outputMessageName11()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName12
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] disableSubscription1;
        
        public inputMessageName12()
        {
        }
        
        public inputMessageName12(int[] disableSubscription1)
        {
            this.disableSubscription1 = disableSubscription1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName12
    {
        
        public outputMessageName12()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName13
    {
        
        public inputMessageName13()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName13
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.OpenApi.WSDatalineResource[] getDatalineInputIDs1;
        
        public outputMessageName13()
        {
        }
        
        public outputMessageName13(Ihc.Soap.OpenApi.WSDatalineResource[] getDatalineInputIDs1)
        {
            this.getDatalineInputIDs1 = getDatalineInputIDs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName14
    {
        
        public inputMessageName14()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName14
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.OpenApi.WSDatalineResource[] getDatalineOutputIDs1;
        
        public outputMessageName14()
        {
        }
        
        public outputMessageName14(Ihc.Soap.OpenApi.WSDatalineResource[] getDatalineOutputIDs1)
        {
            this.getDatalineOutputIDs1 = getDatalineOutputIDs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName15
    {
        
        public inputMessageName15()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName15
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isIHCProjectAvailable1;
        
        public outputMessageName15()
        {
        }
        
        public outputMessageName15(System.Nullable<bool> isIHCProjectAvailable1)
        {
            this.isIHCProjectAvailable1 = isIHCProjectAvailable1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName16
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegment3;
        
        public inputMessageName16()
        {
        }
        
        public inputMessageName16(System.Nullable<int> getIHCProjectSegment1, System.Nullable<int> getIHCProjectSegment2, System.Nullable<int> getIHCProjectSegment3)
        {
            this.getIHCProjectSegment1 = getIHCProjectSegment1;
            this.getIHCProjectSegment2 = getIHCProjectSegment2;
            this.getIHCProjectSegment3 = getIHCProjectSegment3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName16
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSFile getIHCProjectSegment4;
        
        public outputMessageName16()
        {
        }
        
        public outputMessageName16(Ihc.Soap.OpenApi.WSFile getIHCProjectSegment4)
        {
            this.getIHCProjectSegment4 = getIHCProjectSegment4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName17
    {
        
        public inputMessageName17()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName17
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectSegmentationSize1;
        
        public outputMessageName17()
        {
        }
        
        public outputMessageName17(System.Nullable<int> getIHCProjectSegmentationSize1)
        {
            this.getIHCProjectSegmentationSize1 = getIHCProjectSegmentationSize1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName18
    {
        
        public inputMessageName18()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName18
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getIHCProjectNumberOfSegments1;
        
        public outputMessageName18()
        {
        }
        
        public outputMessageName18(System.Nullable<int> getIHCProjectNumberOfSegments1)
        {
            this.getIHCProjectNumberOfSegments1 = getIHCProjectNumberOfSegments1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName19
    {
        
        public inputMessageName19()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName19
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSSceneProjectInfo getSceneProjectInfo1;
        
        public outputMessageName19()
        {
        }
        
        public outputMessageName19(Ihc.Soap.OpenApi.WSSceneProjectInfo getSceneProjectInfo1)
        {
            this.getSceneProjectInfo1 = getSceneProjectInfo1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName20
    {
        
        public inputMessageName20()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName20
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getSceneProjectSegmentationSize1;
        
        public outputMessageName20()
        {
        }
        
        public outputMessageName20(System.Nullable<int> getSceneProjectSegmentationSize1)
        {
            this.getSceneProjectSegmentationSize1 = getSceneProjectSegmentationSize1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName21
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getSceneProjectSegment1;
        
        public inputMessageName21()
        {
        }
        
        public inputMessageName21(System.Nullable<int> getSceneProjectSegment1)
        {
            this.getSceneProjectSegment1 = getSceneProjectSegment1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName21
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.OpenApi.WSFile getSceneProjectSegment2;
        
        public outputMessageName21()
        {
        }
        
        public outputMessageName21(Ihc.Soap.OpenApi.WSFile getSceneProjectSegment2)
        {
            this.getSceneProjectSegment2 = getSceneProjectSegment2;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface OpenAPIServiceChannel : Ihc.Soap.OpenApi.OpenAPIService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OpenAPIServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.OpenApi.OpenAPIService>, Ihc.Soap.OpenApi.OpenAPIService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OpenAPIServiceClient() : 
                base(OpenAPIServiceClient.GetDefaultBinding(), OpenAPIServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OpenAPIServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenAPIServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OpenAPIServiceClient.GetBindingForEndpoint(endpointConfiguration), OpenAPIServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenAPIServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OpenAPIServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenAPIServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OpenAPIServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpenAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName1> Ihc.Soap.OpenApi.OpenAPIService.setValuesAsync(Ihc.Soap.OpenApi.inputMessageName1 request)
        {
            return base.Channel.setValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName1> setValuesAsync(Ihc.Soap.OpenApi.WSResourceValueEvent[] setValues1)
        {
            Ihc.Soap.OpenApi.inputMessageName1 inValue = new Ihc.Soap.OpenApi.inputMessageName1();
            inValue.setValues1 = setValues1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).setValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName2> Ihc.Soap.OpenApi.OpenAPIService.getValuesAsync(Ihc.Soap.OpenApi.inputMessageName2 request)
        {
            return base.Channel.getValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName2> getValuesAsync(int[] getValues1)
        {
            Ihc.Soap.OpenApi.inputMessageName2 inValue = new Ihc.Soap.OpenApi.inputMessageName2();
            inValue.getValues1 = getValues1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName3> Ihc.Soap.OpenApi.OpenAPIService.waitForEventsAsync(Ihc.Soap.OpenApi.inputMessageName3 request)
        {
            return base.Channel.waitForEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName3> waitForEventsAsync(System.Nullable<int> waitForEvents1)
        {
            Ihc.Soap.OpenApi.inputMessageName3 inValue = new Ihc.Soap.OpenApi.inputMessageName3();
            inValue.waitForEvents1 = waitForEvents1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).waitForEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName4> Ihc.Soap.OpenApi.OpenAPIService.getTimeAsync(Ihc.Soap.OpenApi.inputMessageName4 request)
        {
            return base.Channel.getTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName4> getTimeAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName4 inValue = new Ihc.Soap.OpenApi.inputMessageName4();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName5> Ihc.Soap.OpenApi.OpenAPIService.getUptimeAsync(Ihc.Soap.OpenApi.inputMessageName5 request)
        {
            return base.Channel.getUptimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName5> getUptimeAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName5 inValue = new Ihc.Soap.OpenApi.inputMessageName5();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getUptimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName6> Ihc.Soap.OpenApi.OpenAPIService.pingAsync(Ihc.Soap.OpenApi.inputMessageName6 request)
        {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName6> pingAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName6 inValue = new Ihc.Soap.OpenApi.inputMessageName6();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).pingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName7> Ihc.Soap.OpenApi.OpenAPIService.getFWVersionAsync(Ihc.Soap.OpenApi.inputMessageName7 request)
        {
            return base.Channel.getFWVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName7> getFWVersionAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName7 inValue = new Ihc.Soap.OpenApi.inputMessageName7();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getFWVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName8> Ihc.Soap.OpenApi.OpenAPIService.getAPIVersionAsync(Ihc.Soap.OpenApi.inputMessageName8 request)
        {
            return base.Channel.getAPIVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName8> getAPIVersionAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName8 inValue = new Ihc.Soap.OpenApi.inputMessageName8();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getAPIVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName9> Ihc.Soap.OpenApi.OpenAPIService.authenticateAsync(Ihc.Soap.OpenApi.inputMessageName9 request)
        {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName9> authenticateAsync(string authenticate1, string authenticate2)
        {
            Ihc.Soap.OpenApi.inputMessageName9 inValue = new Ihc.Soap.OpenApi.inputMessageName9();
            inValue.authenticate1 = authenticate1;
            inValue.authenticate2 = authenticate2;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).authenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName10> Ihc.Soap.OpenApi.OpenAPIService.getProjectInfoAsync(Ihc.Soap.OpenApi.inputMessageName10 request)
        {
            return base.Channel.getProjectInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName10> getProjectInfoAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName10 inValue = new Ihc.Soap.OpenApi.inputMessageName10();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getProjectInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName11> Ihc.Soap.OpenApi.OpenAPIService.enableSubscriptionAsync(Ihc.Soap.OpenApi.inputMessageName11 request)
        {
            return base.Channel.enableSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName11> enableSubscriptionAsync(int[] enableSubscription1)
        {
            Ihc.Soap.OpenApi.inputMessageName11 inValue = new Ihc.Soap.OpenApi.inputMessageName11();
            inValue.enableSubscription1 = enableSubscription1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).enableSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName12> Ihc.Soap.OpenApi.OpenAPIService.disableSubscriptionAsync(Ihc.Soap.OpenApi.inputMessageName12 request)
        {
            return base.Channel.disableSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName12> disableSubscriptionAsync(int[] disableSubscription1)
        {
            Ihc.Soap.OpenApi.inputMessageName12 inValue = new Ihc.Soap.OpenApi.inputMessageName12();
            inValue.disableSubscription1 = disableSubscription1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).disableSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName13> Ihc.Soap.OpenApi.OpenAPIService.getDatalineInputIDsAsync(Ihc.Soap.OpenApi.inputMessageName13 request)
        {
            return base.Channel.getDatalineInputIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName13> getDatalineInputIDsAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName13 inValue = new Ihc.Soap.OpenApi.inputMessageName13();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getDatalineInputIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName14> Ihc.Soap.OpenApi.OpenAPIService.getDatalineOutputIDsAsync(Ihc.Soap.OpenApi.inputMessageName14 request)
        {
            return base.Channel.getDatalineOutputIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName14> getDatalineOutputIDsAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName14 inValue = new Ihc.Soap.OpenApi.inputMessageName14();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getDatalineOutputIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName15> Ihc.Soap.OpenApi.OpenAPIService.isIHCProjectAvailableAsync(Ihc.Soap.OpenApi.inputMessageName15 request)
        {
            return base.Channel.isIHCProjectAvailableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName15> isIHCProjectAvailableAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName15 inValue = new Ihc.Soap.OpenApi.inputMessageName15();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).isIHCProjectAvailableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName16> Ihc.Soap.OpenApi.OpenAPIService.getIHCProjectSegmentAsync(Ihc.Soap.OpenApi.inputMessageName16 request)
        {
            return base.Channel.getIHCProjectSegmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName16> getIHCProjectSegmentAsync(System.Nullable<int> getIHCProjectSegment1, System.Nullable<int> getIHCProjectSegment2, System.Nullable<int> getIHCProjectSegment3)
        {
            Ihc.Soap.OpenApi.inputMessageName16 inValue = new Ihc.Soap.OpenApi.inputMessageName16();
            inValue.getIHCProjectSegment1 = getIHCProjectSegment1;
            inValue.getIHCProjectSegment2 = getIHCProjectSegment2;
            inValue.getIHCProjectSegment3 = getIHCProjectSegment3;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getIHCProjectSegmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName17> Ihc.Soap.OpenApi.OpenAPIService.getIHCProjectSegmentationSizeAsync(Ihc.Soap.OpenApi.inputMessageName17 request)
        {
            return base.Channel.getIHCProjectSegmentationSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName17> getIHCProjectSegmentationSizeAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName17 inValue = new Ihc.Soap.OpenApi.inputMessageName17();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getIHCProjectSegmentationSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName18> Ihc.Soap.OpenApi.OpenAPIService.getIHCProjectNumberOfSegmentsAsync(Ihc.Soap.OpenApi.inputMessageName18 request)
        {
            return base.Channel.getIHCProjectNumberOfSegmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName18> getIHCProjectNumberOfSegmentsAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName18 inValue = new Ihc.Soap.OpenApi.inputMessageName18();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getIHCProjectNumberOfSegmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName19> Ihc.Soap.OpenApi.OpenAPIService.getSceneProjectInfoAsync(Ihc.Soap.OpenApi.inputMessageName19 request)
        {
            return base.Channel.getSceneProjectInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName19> getSceneProjectInfoAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName19 inValue = new Ihc.Soap.OpenApi.inputMessageName19();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getSceneProjectInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName20> Ihc.Soap.OpenApi.OpenAPIService.getSceneProjectSegmentationSizeAsync(Ihc.Soap.OpenApi.inputMessageName20 request)
        {
            return base.Channel.getSceneProjectSegmentationSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName20> getSceneProjectSegmentationSizeAsync()
        {
            Ihc.Soap.OpenApi.inputMessageName20 inValue = new Ihc.Soap.OpenApi.inputMessageName20();
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getSceneProjectSegmentationSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName21> Ihc.Soap.OpenApi.OpenAPIService.getSceneProjectSegmentAsync(Ihc.Soap.OpenApi.inputMessageName21 request)
        {
            return base.Channel.getSceneProjectSegmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.OpenApi.outputMessageName21> getSceneProjectSegmentAsync(System.Nullable<int> getSceneProjectSegment1)
        {
            Ihc.Soap.OpenApi.inputMessageName21 inValue = new Ihc.Soap.OpenApi.inputMessageName21();
            inValue.getSceneProjectSegment1 = getSceneProjectSegment1;
            return ((Ihc.Soap.OpenApi.OpenAPIService)(this)).getSceneProjectSegmentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OpenAPIServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OpenAPIServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/OpenAPIService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OpenAPIServiceClient.GetBindingForEndpoint(EndpointConfiguration.OpenAPIServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OpenAPIServiceClient.GetEndpointAddress(EndpointConfiguration.OpenAPIServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            OpenAPIServiceBindingPort,
        }
    }
}
