//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihc.Soap.Resources
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="utcs", ConfigurationName="Ihc.Soap.Resources.ResourceInteractionService")]
    public interface ResourceInteractionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getScenePositionsForSceneValueResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName1> getScenePositionsForSceneValueResourceAsync(Ihc.Soap.Resources.inputMessageName1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSceneGroupResourceIdAndPositions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName2> getSceneGroupResourceIdAndPositionsAsync(Ihc.Soap.Resources.inputMessageName2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="setResourceValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName3> setResourceValuesAsync(Ihc.Soap.Resources.inputMessageName3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enableRuntimeValueNotifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName4> enableRuntimeValueNotificationsAsync(Ihc.Soap.Resources.inputMessageName4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="disableRuntimeValueNotifactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName5> disableRuntimeValueNotifactionsAsync(Ihc.Soap.Resources.inputMessageName5 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enableInitialValueNotifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName6> enableInitialValueNotificationsAsync(Ihc.Soap.Resources.inputMessageName6 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="disableInitialValueNotifactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName7> disableInitialValueNotifactionsAsync(Ihc.Soap.Resources.inputMessageName7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="waitForResourceValueChanges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName8> waitForResourceValueChangesAsync(Ihc.Soap.Resources.inputMessageName8 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEnumeratorDefinitions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName9> getEnumeratorDefinitionsAsync(Ihc.Soap.Resources.inputMessageName9 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getExtraDatalineInputs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName10> getExtraDatalineInputsAsync(Ihc.Soap.Resources.inputMessageName10 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getExtraDatalineOutputs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName11> getExtraDatalineOutputsAsync(Ihc.Soap.Resources.inputMessageName11 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAllDatalineInputs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName12> getAllDatalineInputsAsync(Ihc.Soap.Resources.inputMessageName12 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAllDatalineOutputs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName13> getAllDatalineOutputsAsync(Ihc.Soap.Resources.inputMessageName13 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getRuntimeValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName14> getRuntimeValueAsync(Ihc.Soap.Resources.inputMessageName14 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getInitialValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName15> getInitialValuesAsync(Ihc.Soap.Resources.inputMessageName15 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getInitialValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName16> getInitialValueAsync(Ihc.Soap.Resources.inputMessageName16 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getRuntimeValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName17> getRuntimeValuesAsync(Ihc.Soap.Resources.inputMessageName17 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="setResourceValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName18> setResourceValueAsync(Ihc.Soap.Resources.inputMessageName18 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getResourceType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName19> getResourceTypeAsync(Ihc.Soap.Resources.inputMessageName19 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSSceneResourceIdAndLocationURLs
    {
        
        private string scenePositionSeenFromFunctionBlockField;
        
        private int sceneResourceIdField;
        
        private string scenePositionSeenFromProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scenePositionSeenFromFunctionBlock
        {
            get
            {
                return this.scenePositionSeenFromFunctionBlockField;
            }
            set
            {
                this.scenePositionSeenFromFunctionBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int sceneResourceId
        {
            get
            {
                return this.sceneResourceIdField;
            }
            set
            {
                this.sceneResourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string scenePositionSeenFromProduct
        {
            get
            {
                return this.scenePositionSeenFromProductField;
            }
            set
            {
                this.scenePositionSeenFromProductField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSDatalineResource
    {
        
        private int datalineNumberField;
        
        private int resourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int datalineNumber
        {
            get
            {
                return this.datalineNumberField;
            }
            set
            {
                this.datalineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int resourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSEnumDefinition
    {
        
        private int enumeratorDefinitionIDField;
        
        private WSEnumValue[] enumeratorValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int enumeratorDefinitionID
        {
            get
            {
                return this.enumeratorDefinitionIDField;
            }
            set
            {
                this.enumeratorDefinitionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public WSEnumValue[] enumeratorValues
        {
            get
            {
                return this.enumeratorValuesField;
            }
            set
            {
                this.enumeratorValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSEnumValue : WSResourceValue
    {
        
        private int definitionTypeIDField;
        
        private int enumValueIDField;
        
        private string enumNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int definitionTypeID
        {
            get
            {
                return this.definitionTypeIDField;
            }
            set
            {
                this.definitionTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int enumValueID
        {
            get
            {
                return this.enumValueIDField;
            }
            set
            {
                this.enumValueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string enumName
        {
            get
            {
                return this.enumNameField;
            }
            set
            {
                this.enumNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSBooleanValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSDateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSFloatingPointValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSIntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSPhoneNumberValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneDimmerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneRelayValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSceneShutterSimpleValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSTimerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSTimeValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSWeekdayValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSEnumValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSResourceValue
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSBooleanValue : WSResourceValue
    {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSDateValue : WSResourceValue
    {
        
        private short yearField;
        
        private sbyte monthField;
        
        private sbyte dayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sbyte month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public sbyte day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSFloatingPointValue : WSResourceValue
    {
        
        private double floatingPointValueField;
        
        private double maximumValueField;
        
        private double minimumValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double floatingPointValue
        {
            get
            {
                return this.floatingPointValueField;
            }
            set
            {
                this.floatingPointValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double maximumValue
        {
            get
            {
                return this.maximumValueField;
            }
            set
            {
                this.maximumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double minimumValue
        {
            get
            {
                return this.minimumValueField;
            }
            set
            {
                this.minimumValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSIntegerValue : WSResourceValue
    {
        
        private int integerField;
        
        private int maximumValueField;
        
        private int minimumValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int integer
        {
            get
            {
                return this.integerField;
            }
            set
            {
                this.integerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maximumValue
        {
            get
            {
                return this.maximumValueField;
            }
            set
            {
                this.maximumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int minimumValue
        {
            get
            {
                return this.minimumValueField;
            }
            set
            {
                this.minimumValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSPhoneNumberValue : WSResourceValue
    {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneDimmerValue : WSResourceValue
    {
        
        private int delayTimeField;
        
        private int rampTimeField;
        
        private int dimmerPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int rampTime
        {
            get
            {
                return this.rampTimeField;
            }
            set
            {
                this.rampTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int dimmerPercentage
        {
            get
            {
                return this.dimmerPercentageField;
            }
            set
            {
                this.dimmerPercentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneRelayValue : WSResourceValue
    {
        
        private int delayTimeField;
        
        private bool relayValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool relayValue
        {
            get
            {
                return this.relayValueField;
            }
            set
            {
                this.relayValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSSceneShutterSimpleValue : WSResourceValue
    {
        
        private int delayTimeField;
        
        private bool shutterPositionIsUpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int delayTime
        {
            get
            {
                return this.delayTimeField;
            }
            set
            {
                this.delayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool shutterPositionIsUp
        {
            get
            {
                return this.shutterPositionIsUpField;
            }
            set
            {
                this.shutterPositionIsUpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSTimerValue : WSResourceValue
    {
        
        private long millisecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long milliseconds
        {
            get
            {
                return this.millisecondsField;
            }
            set
            {
                this.millisecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSTimeValue : WSResourceValue
    {
        
        private int hoursField;
        
        private int minutesField;
        
        private int secondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs.values")]
    public partial class WSWeekdayValue : WSResourceValue
    {
        
        private int weekdayNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int weekdayNumber
        {
            get
            {
                return this.weekdayNumberField;
            }
            set
            {
                this.weekdayNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="utcs")]
    public partial class WSResourceValueEnvelope
    {
        
        private WSResourceValue valueField;
        
        private string typeStringField;
        
        private int resourceIDField;
        
        private bool isValueRuntimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public WSResourceValue value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string typeString
        {
            get
            {
                return this.typeStringField;
            }
            set
            {
                this.typeStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int resourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isValueRuntime
        {
            get
            {
                return this.isValueRuntimeField;
            }
            set
            {
                this.isValueRuntimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getScenePositionsForSceneValueResource1;
        
        public inputMessageName1()
        {
        }
        
        public inputMessageName1(System.Nullable<int> getScenePositionsForSceneValueResource1)
        {
            this.getScenePositionsForSceneValueResource1 = getScenePositionsForSceneValueResource1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Resources.WSSceneResourceIdAndLocationURLs getScenePositionsForSceneValueResource2;
        
        public outputMessageName1()
        {
        }
        
        public outputMessageName1(Ihc.Soap.Resources.WSSceneResourceIdAndLocationURLs getScenePositionsForSceneValueResource2)
        {
            this.getScenePositionsForSceneValueResource2 = getScenePositionsForSceneValueResource2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getSceneGroupResourceIdAndPositions1;
        
        public inputMessageName2()
        {
        }
        
        public inputMessageName2(System.Nullable<int> getSceneGroupResourceIdAndPositions1)
        {
            this.getSceneGroupResourceIdAndPositions1 = getSceneGroupResourceIdAndPositions1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSSceneResourceIdAndLocationURLs[] getSceneGroupResourceIdAndPositions2;
        
        public outputMessageName2()
        {
        }
        
        public outputMessageName2(Ihc.Soap.Resources.WSSceneResourceIdAndLocationURLs[] getSceneGroupResourceIdAndPositions2)
        {
            this.getSceneGroupResourceIdAndPositions2 = getSceneGroupResourceIdAndPositions2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] setResourceValues1;
        
        public inputMessageName3()
        {
        }
        
        public inputMessageName3(Ihc.Soap.Resources.WSResourceValueEnvelope[] setResourceValues1)
        {
            this.setResourceValues1 = setResourceValues1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> setResourceValues2;
        
        public outputMessageName3()
        {
        }
        
        public outputMessageName3(System.Nullable<bool> setResourceValues2)
        {
            this.setResourceValues2 = setResourceValues2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] enableRuntimeValueNotifications1;
        
        public inputMessageName4()
        {
        }
        
        public inputMessageName4(int[] enableRuntimeValueNotifications1)
        {
            this.enableRuntimeValueNotifications1 = enableRuntimeValueNotifications1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName4
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] enableRuntimeValueNotifications2;
        
        public outputMessageName4()
        {
        }
        
        public outputMessageName4(Ihc.Soap.Resources.WSResourceValueEnvelope[] enableRuntimeValueNotifications2)
        {
            this.enableRuntimeValueNotifications2 = enableRuntimeValueNotifications2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] disableRuntimeValueNotifactions1;
        
        public inputMessageName5()
        {
        }
        
        public inputMessageName5(int[] disableRuntimeValueNotifactions1)
        {
            this.disableRuntimeValueNotifactions1 = disableRuntimeValueNotifactions1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName5
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> disableRuntimeValueNotifactions2;
        
        public outputMessageName5()
        {
        }
        
        public outputMessageName5(System.Nullable<bool> disableRuntimeValueNotifactions2)
        {
            this.disableRuntimeValueNotifactions2 = disableRuntimeValueNotifactions2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] enableInitialValueNotifications1;
        
        public inputMessageName6()
        {
        }
        
        public inputMessageName6(int[] enableInitialValueNotifications1)
        {
            this.enableInitialValueNotifications1 = enableInitialValueNotifications1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName6
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] enableInitialValueNotifications2;
        
        public outputMessageName6()
        {
        }
        
        public outputMessageName6(Ihc.Soap.Resources.WSResourceValueEnvelope[] enableInitialValueNotifications2)
        {
            this.enableInitialValueNotifications2 = enableInitialValueNotifications2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] disableInitialValueNotifactions1;
        
        public inputMessageName7()
        {
        }
        
        public inputMessageName7(int[] disableInitialValueNotifactions1)
        {
            this.disableInitialValueNotifactions1 = disableInitialValueNotifactions1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName7
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> disableInitialValueNotifactions2;
        
        public outputMessageName7()
        {
        }
        
        public outputMessageName7(System.Nullable<bool> disableInitialValueNotifactions2)
        {
            this.disableInitialValueNotifactions2 = disableInitialValueNotifactions2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName8
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> waitForResourceValueChanges1;
        
        public inputMessageName8()
        {
        }
        
        public inputMessageName8(System.Nullable<int> waitForResourceValueChanges1)
        {
            this.waitForResourceValueChanges1 = waitForResourceValueChanges1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName8
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] waitForResourceValueChanges2;
        
        public outputMessageName8()
        {
        }
        
        public outputMessageName8(Ihc.Soap.Resources.WSResourceValueEnvelope[] waitForResourceValueChanges2)
        {
            this.waitForResourceValueChanges2 = waitForResourceValueChanges2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName9
    {
        
        public inputMessageName9()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName9
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="utcs.values")]
        public Ihc.Soap.Resources.WSEnumDefinition[] getEnumeratorDefinitions1;
        
        public outputMessageName9()
        {
        }
        
        public outputMessageName9(Ihc.Soap.Resources.WSEnumDefinition[] getEnumeratorDefinitions1)
        {
            this.getEnumeratorDefinitions1 = getEnumeratorDefinitions1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName10
    {
        
        public inputMessageName10()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName10
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSDatalineResource[] getExtraDatalineInputs1;
        
        public outputMessageName10()
        {
        }
        
        public outputMessageName10(Ihc.Soap.Resources.WSDatalineResource[] getExtraDatalineInputs1)
        {
            this.getExtraDatalineInputs1 = getExtraDatalineInputs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName11
    {
        
        public inputMessageName11()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName11
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSDatalineResource[] getExtraDatalineOutputs1;
        
        public outputMessageName11()
        {
        }
        
        public outputMessageName11(Ihc.Soap.Resources.WSDatalineResource[] getExtraDatalineOutputs1)
        {
            this.getExtraDatalineOutputs1 = getExtraDatalineOutputs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName12
    {
        
        public inputMessageName12()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName12
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSDatalineResource[] getAllDatalineInputs1;
        
        public outputMessageName12()
        {
        }
        
        public outputMessageName12(Ihc.Soap.Resources.WSDatalineResource[] getAllDatalineInputs1)
        {
            this.getAllDatalineInputs1 = getAllDatalineInputs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName13
    {
        
        public inputMessageName13()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName13
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSDatalineResource[] getAllDatalineOutputs1;
        
        public outputMessageName13()
        {
        }
        
        public outputMessageName13(Ihc.Soap.Resources.WSDatalineResource[] getAllDatalineOutputs1)
        {
            this.getAllDatalineOutputs1 = getAllDatalineOutputs1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName14
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getRuntimeValue1;
        
        public inputMessageName14()
        {
        }
        
        public inputMessageName14(System.Nullable<int> getRuntimeValue1)
        {
            this.getRuntimeValue1 = getRuntimeValue1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName14
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Resources.WSResourceValueEnvelope getRuntimeValue2;
        
        public outputMessageName14()
        {
        }
        
        public outputMessageName14(Ihc.Soap.Resources.WSResourceValueEnvelope getRuntimeValue2)
        {
            this.getRuntimeValue2 = getRuntimeValue2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName15
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] getInitialValues1;
        
        public inputMessageName15()
        {
        }
        
        public inputMessageName15(int[] getInitialValues1)
        {
            this.getInitialValues1 = getInitialValues1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName15
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] getInitialValues2;
        
        public outputMessageName15()
        {
        }
        
        public outputMessageName15(Ihc.Soap.Resources.WSResourceValueEnvelope[] getInitialValues2)
        {
            this.getInitialValues2 = getInitialValues2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName16
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getInitialValue1;
        
        public inputMessageName16()
        {
        }
        
        public inputMessageName16(System.Nullable<int> getInitialValue1)
        {
            this.getInitialValue1 = getInitialValue1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName16
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Resources.WSResourceValueEnvelope getInitialValue2;
        
        public outputMessageName16()
        {
        }
        
        public outputMessageName16(Ihc.Soap.Resources.WSResourceValueEnvelope getInitialValue2)
        {
            this.getInitialValue2 = getInitialValue2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName17
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem", Namespace="http://www.w3.org/2001/XMLSchema", IsNullable=false)]
        public int[] getRuntimeValues1;
        
        public inputMessageName17()
        {
        }
        
        public inputMessageName17(int[] getRuntimeValues1)
        {
            this.getRuntimeValues1 = getRuntimeValues1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName17
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayItem")]
        public Ihc.Soap.Resources.WSResourceValueEnvelope[] getRuntimeValues2;
        
        public outputMessageName17()
        {
        }
        
        public outputMessageName17(Ihc.Soap.Resources.WSResourceValueEnvelope[] getRuntimeValues2)
        {
            this.getRuntimeValues2 = getRuntimeValues2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName18
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ihc.Soap.Resources.WSResourceValueEnvelope setResourceValue1;
        
        public inputMessageName18()
        {
        }
        
        public inputMessageName18(Ihc.Soap.Resources.WSResourceValueEnvelope setResourceValue1)
        {
            this.setResourceValue1 = setResourceValue1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName18
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> setResourceValue2;
        
        public outputMessageName18()
        {
        }
        
        public outputMessageName18(System.Nullable<bool> setResourceValue2)
        {
            this.setResourceValue2 = setResourceValue2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputMessageName19
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> getResourceType1;
        
        public inputMessageName19()
        {
        }
        
        public inputMessageName19(System.Nullable<int> getResourceType1)
        {
            this.getResourceType1 = getResourceType1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputMessageName19
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="utcs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getResourceType2;
        
        public outputMessageName19()
        {
        }
        
        public outputMessageName19(string getResourceType2)
        {
            this.getResourceType2 = getResourceType2;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ResourceInteractionServiceChannel : Ihc.Soap.Resources.ResourceInteractionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ResourceInteractionServiceClient : System.ServiceModel.ClientBase<Ihc.Soap.Resources.ResourceInteractionService>, Ihc.Soap.Resources.ResourceInteractionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ResourceInteractionServiceClient() : 
                base(ResourceInteractionServiceClient.GetDefaultBinding(), ResourceInteractionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ResourceInteractionServiceBindingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ResourceInteractionServiceClient.GetBindingForEndpoint(endpointConfiguration), ResourceInteractionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ResourceInteractionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ResourceInteractionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName1> Ihc.Soap.Resources.ResourceInteractionService.getScenePositionsForSceneValueResourceAsync(Ihc.Soap.Resources.inputMessageName1 request)
        {
            return base.Channel.getScenePositionsForSceneValueResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName1> getScenePositionsForSceneValueResourceAsync(System.Nullable<int> getScenePositionsForSceneValueResource1)
        {
            Ihc.Soap.Resources.inputMessageName1 inValue = new Ihc.Soap.Resources.inputMessageName1();
            inValue.getScenePositionsForSceneValueResource1 = getScenePositionsForSceneValueResource1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getScenePositionsForSceneValueResourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName2> Ihc.Soap.Resources.ResourceInteractionService.getSceneGroupResourceIdAndPositionsAsync(Ihc.Soap.Resources.inputMessageName2 request)
        {
            return base.Channel.getSceneGroupResourceIdAndPositionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName2> getSceneGroupResourceIdAndPositionsAsync(System.Nullable<int> getSceneGroupResourceIdAndPositions1)
        {
            Ihc.Soap.Resources.inputMessageName2 inValue = new Ihc.Soap.Resources.inputMessageName2();
            inValue.getSceneGroupResourceIdAndPositions1 = getSceneGroupResourceIdAndPositions1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getSceneGroupResourceIdAndPositionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName3> Ihc.Soap.Resources.ResourceInteractionService.setResourceValuesAsync(Ihc.Soap.Resources.inputMessageName3 request)
        {
            return base.Channel.setResourceValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName3> setResourceValuesAsync(Ihc.Soap.Resources.WSResourceValueEnvelope[] setResourceValues1)
        {
            Ihc.Soap.Resources.inputMessageName3 inValue = new Ihc.Soap.Resources.inputMessageName3();
            inValue.setResourceValues1 = setResourceValues1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).setResourceValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName4> Ihc.Soap.Resources.ResourceInteractionService.enableRuntimeValueNotificationsAsync(Ihc.Soap.Resources.inputMessageName4 request)
        {
            return base.Channel.enableRuntimeValueNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName4> enableRuntimeValueNotificationsAsync(int[] enableRuntimeValueNotifications1)
        {
            Ihc.Soap.Resources.inputMessageName4 inValue = new Ihc.Soap.Resources.inputMessageName4();
            inValue.enableRuntimeValueNotifications1 = enableRuntimeValueNotifications1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).enableRuntimeValueNotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName5> Ihc.Soap.Resources.ResourceInteractionService.disableRuntimeValueNotifactionsAsync(Ihc.Soap.Resources.inputMessageName5 request)
        {
            return base.Channel.disableRuntimeValueNotifactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName5> disableRuntimeValueNotifactionsAsync(int[] disableRuntimeValueNotifactions1)
        {
            Ihc.Soap.Resources.inputMessageName5 inValue = new Ihc.Soap.Resources.inputMessageName5();
            inValue.disableRuntimeValueNotifactions1 = disableRuntimeValueNotifactions1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).disableRuntimeValueNotifactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName6> Ihc.Soap.Resources.ResourceInteractionService.enableInitialValueNotificationsAsync(Ihc.Soap.Resources.inputMessageName6 request)
        {
            return base.Channel.enableInitialValueNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName6> enableInitialValueNotificationsAsync(int[] enableInitialValueNotifications1)
        {
            Ihc.Soap.Resources.inputMessageName6 inValue = new Ihc.Soap.Resources.inputMessageName6();
            inValue.enableInitialValueNotifications1 = enableInitialValueNotifications1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).enableInitialValueNotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName7> Ihc.Soap.Resources.ResourceInteractionService.disableInitialValueNotifactionsAsync(Ihc.Soap.Resources.inputMessageName7 request)
        {
            return base.Channel.disableInitialValueNotifactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName7> disableInitialValueNotifactionsAsync(int[] disableInitialValueNotifactions1)
        {
            Ihc.Soap.Resources.inputMessageName7 inValue = new Ihc.Soap.Resources.inputMessageName7();
            inValue.disableInitialValueNotifactions1 = disableInitialValueNotifactions1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).disableInitialValueNotifactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName8> Ihc.Soap.Resources.ResourceInteractionService.waitForResourceValueChangesAsync(Ihc.Soap.Resources.inputMessageName8 request)
        {
            return base.Channel.waitForResourceValueChangesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName8> waitForResourceValueChangesAsync(System.Nullable<int> waitForResourceValueChanges1)
        {
            Ihc.Soap.Resources.inputMessageName8 inValue = new Ihc.Soap.Resources.inputMessageName8();
            inValue.waitForResourceValueChanges1 = waitForResourceValueChanges1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).waitForResourceValueChangesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName9> Ihc.Soap.Resources.ResourceInteractionService.getEnumeratorDefinitionsAsync(Ihc.Soap.Resources.inputMessageName9 request)
        {
            return base.Channel.getEnumeratorDefinitionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName9> getEnumeratorDefinitionsAsync()
        {
            Ihc.Soap.Resources.inputMessageName9 inValue = new Ihc.Soap.Resources.inputMessageName9();
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getEnumeratorDefinitionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName10> Ihc.Soap.Resources.ResourceInteractionService.getExtraDatalineInputsAsync(Ihc.Soap.Resources.inputMessageName10 request)
        {
            return base.Channel.getExtraDatalineInputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName10> getExtraDatalineInputsAsync()
        {
            Ihc.Soap.Resources.inputMessageName10 inValue = new Ihc.Soap.Resources.inputMessageName10();
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getExtraDatalineInputsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName11> Ihc.Soap.Resources.ResourceInteractionService.getExtraDatalineOutputsAsync(Ihc.Soap.Resources.inputMessageName11 request)
        {
            return base.Channel.getExtraDatalineOutputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName11> getExtraDatalineOutputsAsync()
        {
            Ihc.Soap.Resources.inputMessageName11 inValue = new Ihc.Soap.Resources.inputMessageName11();
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getExtraDatalineOutputsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName12> Ihc.Soap.Resources.ResourceInteractionService.getAllDatalineInputsAsync(Ihc.Soap.Resources.inputMessageName12 request)
        {
            return base.Channel.getAllDatalineInputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName12> getAllDatalineInputsAsync()
        {
            Ihc.Soap.Resources.inputMessageName12 inValue = new Ihc.Soap.Resources.inputMessageName12();
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getAllDatalineInputsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName13> Ihc.Soap.Resources.ResourceInteractionService.getAllDatalineOutputsAsync(Ihc.Soap.Resources.inputMessageName13 request)
        {
            return base.Channel.getAllDatalineOutputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName13> getAllDatalineOutputsAsync()
        {
            Ihc.Soap.Resources.inputMessageName13 inValue = new Ihc.Soap.Resources.inputMessageName13();
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getAllDatalineOutputsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName14> Ihc.Soap.Resources.ResourceInteractionService.getRuntimeValueAsync(Ihc.Soap.Resources.inputMessageName14 request)
        {
            return base.Channel.getRuntimeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName14> getRuntimeValueAsync(System.Nullable<int> getRuntimeValue1)
        {
            Ihc.Soap.Resources.inputMessageName14 inValue = new Ihc.Soap.Resources.inputMessageName14();
            inValue.getRuntimeValue1 = getRuntimeValue1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getRuntimeValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName15> Ihc.Soap.Resources.ResourceInteractionService.getInitialValuesAsync(Ihc.Soap.Resources.inputMessageName15 request)
        {
            return base.Channel.getInitialValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName15> getInitialValuesAsync(int[] getInitialValues1)
        {
            Ihc.Soap.Resources.inputMessageName15 inValue = new Ihc.Soap.Resources.inputMessageName15();
            inValue.getInitialValues1 = getInitialValues1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getInitialValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName16> Ihc.Soap.Resources.ResourceInteractionService.getInitialValueAsync(Ihc.Soap.Resources.inputMessageName16 request)
        {
            return base.Channel.getInitialValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName16> getInitialValueAsync(System.Nullable<int> getInitialValue1)
        {
            Ihc.Soap.Resources.inputMessageName16 inValue = new Ihc.Soap.Resources.inputMessageName16();
            inValue.getInitialValue1 = getInitialValue1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getInitialValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName17> Ihc.Soap.Resources.ResourceInteractionService.getRuntimeValuesAsync(Ihc.Soap.Resources.inputMessageName17 request)
        {
            return base.Channel.getRuntimeValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName17> getRuntimeValuesAsync(int[] getRuntimeValues1)
        {
            Ihc.Soap.Resources.inputMessageName17 inValue = new Ihc.Soap.Resources.inputMessageName17();
            inValue.getRuntimeValues1 = getRuntimeValues1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getRuntimeValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName18> Ihc.Soap.Resources.ResourceInteractionService.setResourceValueAsync(Ihc.Soap.Resources.inputMessageName18 request)
        {
            return base.Channel.setResourceValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName18> setResourceValueAsync(Ihc.Soap.Resources.WSResourceValueEnvelope setResourceValue1)
        {
            Ihc.Soap.Resources.inputMessageName18 inValue = new Ihc.Soap.Resources.inputMessageName18();
            inValue.setResourceValue1 = setResourceValue1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).setResourceValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName19> Ihc.Soap.Resources.ResourceInteractionService.getResourceTypeAsync(Ihc.Soap.Resources.inputMessageName19 request)
        {
            return base.Channel.getResourceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ihc.Soap.Resources.outputMessageName19> getResourceTypeAsync(System.Nullable<int> getResourceType1)
        {
            Ihc.Soap.Resources.inputMessageName19 inValue = new Ihc.Soap.Resources.inputMessageName19();
            inValue.getResourceType1 = getResourceType1;
            return ((Ihc.Soap.Resources.ResourceInteractionService)(this)).getResourceTypeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ResourceInteractionServiceBindingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ResourceInteractionServiceBindingPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ResourceInteractionService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ResourceInteractionServiceClient.GetBindingForEndpoint(EndpointConfiguration.ResourceInteractionServiceBindingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ResourceInteractionServiceClient.GetEndpointAddress(EndpointConfiguration.ResourceInteractionServiceBindingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ResourceInteractionServiceBindingPort,
        }
    }
}
